services:
  goshort:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goshort
    ports:
      - "8081:80" # Frontend
    environment:
      DATABASE_URL: postgres://goshort:goshort_password@database:5432/goshort?sslmode=disable
      # Branding customization (optional)
      BRAND_TITLE: "GoShort - URL Shortener"
      BRAND_DESCRIPTION: "A fast and customizable URL shortener"
      BRAND_THEME_COLOR: "#4caf50"
      BRAND_PRIMARY_COLOR: "#3b82f6"
      BRAND_SECONDARY_COLOR: "#10b981"
      BRAND_HEADER_TITLE: "GoShort - URL Shortener"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17-bullseye
    container_name: goshort_db
    restart: always
    environment:
      POSTGRES_USER: goshort
      POSTGRES_PASSWORD: goshort_password
      POSTGRES_DB: goshort
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goshort -d goshort"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
