name: 🛠️ Build, Test & Scan

on:
  pull_request:
    branches:
      - main

jobs:
  build-go:
    name: 🐹 Build Go Project
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🐹 Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 🛠️ Build Go Project
        run: make build

  build-Svelte:
    name: 🌐 Build Svelte Project
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🌐 Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install Svelte Dependencies
        run: |
          cd web
          npm install

      - name: 🖥️ Build Svelte Project
        run: |
          cd web
          npm run build

  test-go:
    name: ✅ Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🐹 Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: ✅ Run Go Tests
        run: make test

      - name: 📊 Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: go-code-coverage
          path: coverage.out

  scan-vulnerabilities:
    name: 🔍 Scan for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🐹 Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: 🔍 Run Golang Security Scanner
        uses: securego/gosec@v2.21.4
        with:
          args: '-no-fail -fmt sarif -out results.sarif ./...'
      
      - name: 📝 Upload SARIF Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: 🌐 Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install Svelte Dependencies
        run: |
          cd ui
          npm install

      - name: 🔍 Run NPM Audit
        run: |
          cd ui
          npm audit --audit-level=high || true
